import useSWR from 'swr';
import { ProductModelType } from '../../lib/generated/zod/schemas';

const mockProducts: ProductModelType[] = [
  {
    id: "1",
    name: "Premium Basketball",
    images: ["https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400"],
    description: "Professional grade basketball with superior grip and durability",
    price: 8999, // in cents
    vendorName: 'FitPlay Sports',
    tags: ["basketball"],
    discount: null,
    sku: "FP-BB-001",
    availableStock: 150,
    category: 'Apparel',
    avgRating: null,
    noOfReviews: null,
    brand: null,
    companies: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    name: "Football Cleats Pro",
    images: ["https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400"],
    description: "High-performance football cleats for professional athletes",
    price: 15999,
    vendorName: 'FitPlay Sports',
    tags: ["footwear"],
    discount: null,
    sku: "FP-FC-002",
    availableStock: 85,
    category: 'Apparel',
    avgRating: null,
    noOfReviews: null,
    brand: null,
    companies: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    name: "Tennis Racket Elite",
    images: ["https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400"],
    description: "Lightweight tennis racket with advanced string technology",
    price: 19999,
    vendorName: 'FitPlay Sports',
    tags: ["tennis"],
    discount: null,
    sku: "FP-TR-003",
    availableStock: 45,
    category: 'Apparel',
    avgRating: null,
    noOfReviews: null,
    brand: null,
    companies: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    name: "Soccer Ball Official",
    images: ["https://images.unsplash.com/photo-1614632537197-38a17061c2bd?w=400"],
    description: "FIFA approved soccer ball for competitive play",
    price: 4999,
    vendorName: 'FitPlay Sports',
    tags: ["soccer"],
    discount: null,
    sku: "FP-SB-004",
    availableStock: 200,
    category: 'Apparel',
    avgRating: null,
    noOfReviews: null,
    brand: null,
    companies: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5",
    name: "Baseball Glove Pro",
    images: ["https://images.unsplash.com/photo-1566577739112-5180d4bf9390?w=400"],
    description: "Premium leather baseball glove for infielders",
    price: 12999,
    vendorName: 'FitPlay Sports',
    tags: ["baseball"],
    discount: null,
    sku: "FP-BG-005",
    availableStock: 60,
    category: 'Apparel',
    avgRating: null,
    noOfReviews: null,
    brand: null,
    companies: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6",
    name: "Volleyball Net System",
    images: ["https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=400"],
    description: "Complete volleyball net system with posts and guy wires",
    price: 29999,
    vendorName: 'FitPlay Sports',
    tags: ["volleyball"],
    discount: null,
    sku: "FP-VN-006",
    availableStock: 25,
    category: 'Apparel',
    avgRating: null,
    noOfReviews: null,
    brand: null,
    companies: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "7",
    name: "Hockey Stick Carbon",
    images: ["https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400"],
    description: "Lightweight carbon fiber hockey stick for enhanced performance",
    price: 17999,
    vendorName: 'FitPlay Sports',
    tags: ["hockey"],
    discount: null,
    sku: "FP-HS-007",
    availableStock: 40,
    category: 'Apparel',
    avgRating: null,
    noOfReviews: null,
    brand: null,
    companies: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "8",
    name: "Swimming Goggles Pro",
    images: ["https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400"],
    description: "Anti-fog swimming goggles with UV protection",
    price: 3999,
    vendorName: 'FitPlay Sports',
    tags: ["swimming"],
    discount: null,
    sku: "FP-SG-008",
    availableStock: 120,
    category: 'Apparel',
    avgRating: null,
    noOfReviews: null,
    brand: null,
    companies: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Mock fetcher function (replace with actual API call later)
const fetchProducts = async (): Promise<ProductModelType[]> => {
  // Simulate API delay
  await new Promise(resolve => setTimeout(resolve, 100));
  return mockProducts;
};

export const useProducts = () => {
  const { data, error, isLoading } = useSWR<ProductModelType[]>('products', fetchProducts, {
    fallbackData: mockProducts, // Return mock data immediately
    revalidateOnFocus: false,
    revalidateOnReconnect: false,
  });

  return {
    products: data || [],
    isLoading,
    error,
    mutate: () => {}, // Placeholder for future use
  };
};