"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { useState } from "react";
import { ToastManager, useToast } from "@/components/ToastManager";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

interface CartItem {
  id: number;
  title: string;
  brand: string;
  credits: number;
  image: string;
  quantity: number;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [cartItems, setCartItems] = useState<CartItem[]>([]);
  const [cartAnimation, setCartAnimation] = useState(false);
  const { toasts, removeToast } = useToast();

  const totalCartItems = cartItems.reduce((total, item) => total + item.quantity, 0);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-background">
          <Navbar cartCount={totalCartItems} cartAnimation={cartAnimation} />
          <ToastManager toasts={toasts} removeToast={removeToast} />

          <main className="pt-16">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
