"use client";

// import { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react";
import { preload } from "swr";
import { fetchProducts } from "./hooks/useProducts";
import ScrollReveal from "@/components/ScrollReveal";
import Script from "next/script";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

preload("products", fetchProducts);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} font-sans antialiased`}
      >
        <SessionProvider>
          {children}
          <ScrollReveal />
        </SessionProvider>
        <Toaster />
        {/* <Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="afterInteractive"></Script> */}
      </body>
    </html>
  );
}
